# Generated by Django 4.2.5 on 2023-09-17 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_assistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="firebase_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(
                max_length=13,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+9627xxxxxxxx'. Only 10 digits allowed.",
                        regex="^\\+9627\\d{8}$",
                    )
                ],
            ),
        ),
    ]
