# Generated by Django 4.2.5 on 2023-09-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_customuser_firebase_token_alter_customuser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistant",
            name="name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
