# Generated by Django 4.2.5 on 2023-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_remove_assistant_name_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="prompt_ar",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="response_ar",
            field=models.TextField(blank=True, null=True),
        ),
    ]
